export const FETCH_PAINTINGS = 'FETCH_PAINTINGS';
export const FETCH_BY_MUSEUM = "FETCH_BY_MUSEUM"
export const SELECT_ACTIVE_PAINTING = 'SELECT_ACTIVE_PAINTING';
export const REMOVE_ACTIVE_PAINTING = "REMOVE_ACTIVE_PAINTING";
